apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - inferenceservice.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ml-platform
      app.kubernetes.io/component: predictive-serving
