image:
  repository: ghcr.io/mlflow/mlflow
  tag: v3.14.0
  pullPolicy: IfNotPresent

replicaCount: 1

storage:
  enabled: true
  size: 10Gi

mlflow:
  backendStoreUri: sqlite:////mlflow/mlflow.db
  artifactsDestination: /mlflow/artifacts

service:
  type: ClusterIP
  port: 5000

metrics:
  enabled: true
  path: /metrics

serviceMonitor:
  enabled: true

networkPolicy:
  enabled: true

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi
