apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-platform-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: ml-platform
  source:
    repoURL: https://github.com/toby0622/ML-Platform-Blueprint.git
    targetRevision: main
    path: platform/helm/ml-platform
    helm:
      releaseName: ml-platform
      valuesObject:
        image:
          tag: "0.1.0"
        config:
          codeRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 5
