apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: rtx4080-super-patch.yaml
    target:
      group: serving.kserve.io
      version: v1beta1
      kind: InferenceService
      name: qwen-llm
